In [1]:
from pandapower.create import (
    create_empty_network,
    create_bus,
    create_gen,
    create_load,
    create_line_from_parameters,
    create_transformer_from_parameters,
    create_ext_grid,
    create_shunt
)

from pandapower.run import runpp

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
#read xlsx file
import pandas as pd

xls = pd.ExcelFile('ieee14bus.xlsx')

xls.sheet_names

sheet = {}

for sheet_name in xls.sheet_names:
    sheet[sheet_name] = xls.parse(sheet_name)

In [3]:
net = create_empty_network()

In [4]:
#read bus data
buses = {}

for i in range(len(sheet['bus'])):
    buses[i] = create_bus(net, vn_kv=sheet['bus']['vn_kv'][i],
                          name=sheet['bus']['name'][i],
                          type=sheet['bus']['type'][i],
                          in_service=sheet['bus']['in_service'][i],
                          max_vm_pu=sheet['bus']['max_vm_pu'][i],
                          min_vm_pu=sheet['bus']['min_vm_pu'][i])
net.bus

     name  vn_kv type  zone  in_service   geo  min_vm_pu  max_vm_pu
0    bus1  132.0    b  None        True  None        0.9        1.1
1    bus2  132.0    b  None        True  None        0.9        1.1
2    bus3  132.0    b  None        True  None        0.9        1.1
3    bus4  132.0    b  None        True  None        0.9        1.1
4    bus5  132.0    b  None        True  None        0.9        1.1
5    bus6   33.0    b  None        True  None        0.9        1.1
6    bus7    1.0    b  None        True  None        0.9        1.1
7    bus8   11.0    b  None        True  None        0.9        1.1
8    bus9   33.0    b  None        True  None        0.9        1.1
9   bus10   33.0    b  None        True  None        0.9        1.1
10  bus11   33.0    b  None        True  None        0.9        1.1
11  bus12   33.0    b  None        True  None        0.9        1.1
12  bus13   33.0    b  None        True  None        0.9        1.1
13  bus14   33.0    b  None        True  None        0.9        1.1

In [5]:
#read generator data
gens = {}

for i in range(len(sheet['gen'])):
    gens[i] = create_gen(net, name=sheet['gen']['name'][i],
                         bus=sheet['gen']['bus'][i],
                         p_mw=sheet['gen']['p_mw'][i],
                         vm_pu=sheet['gen']['vm_pu'][i],
                         sn_mva=sheet['gen']['sn_mva'][i],
                         min_q_mvar=sheet['gen']['min_q_mvar'][i],
                         max_q_mvar=sheet['gen']['max_q_mvar'][i],
                         controllable=sheet['gen']['controllable'][i],
                         in_service=sheet['gen']['in_service'][i],
                         min_p_mw=sheet['gen']['min_p_mw'][i],
                         max_p_mw=sheet['gen']['max_p_mw'][i],
                        )
net.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,controllable,id_q_capability_characteristic,reactive_capability_curve,curve_style,in_service,slack_weight,type,min_p_mw,max_p_mw
0,gen2,1,40.0,1.045,100.0,-40.0,50.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,0.0,80.0
1,gen3,2,0.0,1.010,100.0,0.0,40.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,-1.0,1.0
2,gen4,5,0.0,1.070,100.0,-6.0,24.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,-1.0,1.0
3,gen5,7,0.0,1.090,100.0,-6.0,24.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,-1.0,1.0

In [6]:
#read transformer data
trafos={}

for i in range(len(sheet['trafo'])):
    trafos[i] = create_transformer_from_parameters(net, name=sheet['trafo']['name'][i],
                             hv_bus=sheet['trafo']['hv_bus'][i],
                             lv_bus=sheet['trafo']['lv_bus'][i],
                             sn_mva=sheet['trafo']['sn_mva'][i],
                             vn_hv_kv=sheet['trafo']['vn_hv_kv'][i],
                             vn_lv_kv=sheet['trafo']['vn_lv_kv'][i],
                             vkr_percent=sheet['trafo']['vkr_percent'][i],
                             vk_percent=sheet['trafo']['vk_percent'][i],
                             pfe_kw=sheet['trafo']['pfe_kw'][i],
                             i0_percent=sheet['trafo']['i0_percent'][i],
                             vector_group=sheet['trafo']['vector_group'][i],
                             vk0_percent=sheet['trafo']['vk0_percent'][i],
                             in_service=sheet['trafo']['in_service'][i],
                             shift_degree=sheet['trafo']['shift_degree'][i],
                             tap_side=sheet['trafo']['tap_side'][i],
                             tap_neutral=sheet['trafo']['tap_neutral'][i],
                             tap_max=sheet['trafo']['tap_max'][i],
                             tap_min=sheet['trafo']['tap_min'][i],
                             tap_step_percent=sheet['trafo']['tap_step_percent'][i],
                             max_loading_percent=sheet['trafo']['max_loading_percent'][i]
                            )
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,tap_changer_type,id_characteristic_table,tap_dependency_table,parallel,df,in_service,vk0_percent,vector_group,max_loading_percent,oltc
0,trafo1,None,3,6,100.0,132.0,1.0,20.912,0.20912,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,Ynyn,100.0,False
1,trafo2,None,3,8,100.0,132.0,33.0,55.618,0.55618,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,Ynyn,100.0,False
2,trafo3,None,4,5,100.0,132.0,33.0,25.202,0.25202,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,Ynyn,100.0,False
3,trafo4,None,7,6,100.0,11.0,1.0,17.615,0.17615,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,Ynyn,100.0,False
4,trafo5,None,8,6,100.0,33.0,1.0,11.001,0.11001,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,Ynyn,100.0,False

In [7]:
#read line data
lines={}

for i in range(len(sheet['line'])):
    lines[i]=create_line_from_parameters(net, name=sheet['line']['name'][i],
                                         from_bus=sheet['line']['from_bus'][i],
                                         to_bus=sheet['line']['to_bus'][i],
                                         length_km=sheet['line']['length_km'][i],
                                         r_ohm_per_km=sheet['line']['r_ohm_per_km'][i],
                                         x_ohm_per_km=sheet['line']['x_ohm_per_km'][i],
                                         c_nf_per_km=sheet['line']['c_nf_per_km'][i],
                                         max_i_ka=sheet['line']['max_i_ka'][i],
                                         in_service=sheet['line']['in_service'][i], 
                                         type=sheet['line']['type'][i],
                                         max_loading_percent=sheet['line']['max_loading_percent'][i]
                                        )
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service,geo,max_loading_percent
0,line1-2/1,None,0,1,1.0,6.753,20.620,401.906551,0.0,1.0,1.0,1,ol,True,None,100.0
1,line1-2/2,None,0,1,1.0,6.753,20.620,401.906551,0.0,1.0,1.0,1,ol,True,None,100.0
2,line1-5,None,0,4,1.0,9.414,38.862,749.007301,0.0,1.0,1.0,1,ol,True,None,100.0
3,line2-3,None,1,2,1.0,8.188,34.494,666.799263,0.0,1.0,1.0,1,ol,True,None,100.0
4,line2-4,None,1,3,1.0,10.125,30.722,569.367525,0.0,1.0,1.0,1,ol,True,None,100.0
5,line2-5,None,1,4,1.0,9.923,30.297,517.606624,0.0,1.0,1.0,1,ol,True,None,100.0
6,line3-4,None,2,3,1.0,11.676,29.800,526.741056,0.0,1.0,1.0,1,ol,True,None,100.0
7,line4-5,None,3,4,1.0,2.326,7.337,194.863742,0.0,1.0,1.0,1,ol,True,None,100.0
8,line6-11,None,5,10,1.0,1.034,2.166,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0
9,line6-12,None,5,11,1.0,1.338,2.786,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0
10,line6-13,None,5,12,1.0,0.720,1.419,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0
11,line9-10,None,8,9,1.0,0.346,0.920,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0
12,line9-14,None,8,13,1.0,1.384,2.944,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0
13,line10-11,None,9,10,1.0,0.893,2.092,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0
14,line12-13,None,11,12,1.0,2.406,2.177,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0
15,line13-14,None,12,13,1.0,1.861,3.790,0.000000,0.0,1.0,1.0,1,ol,True,None,100.0

In [8]:
#read load data
loads={}

for i in range(len(sheet['load'])):
    loads[i]=create_load(net, name=sheet['load']['name'][i],
                         bus=sheet['load']['bus'][i],
                         p_mw=sheet['load']['p_mw'][i],
                         q_mvar=sheet['load']['q_mvar'][i],
                         in_service=sheet['load']['in_service'][i],
                         type=sheet['load']['type'][i],
                         controllable=sheet['load']['controllable'][i]
                        )
net.load

,name,bus,p_mw,q_mvar,const_z_p_percent,const_i_p_percent,const_z_q_percent,const_i_q_percent,sn_mva,scaling,in_service,type,controllable
0,load2,1,21.7,12.7,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
1,load3,2,94.2,19.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
2,load4,3,47.8,-3.9,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
3,load5,4,7.6,1.6,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
4,load6,5,11.2,7.5,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
5,load7,6,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
6,load8,7,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
7,load9,8,29.5,16.6,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
8,load10,9,9.0,5.8,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
9,load11,10,3.5,1.8,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
10,load12,11,6.1,1.6,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
11,load13,12,13.5,5.8,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
12,load14,13,14.9,5.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False

In [9]:
#create external grid
grids={}

for i in range(len(sheet['grid'])):
    grids[i]=create_ext_grid(net, name=sheet['grid']['name'][i],
                             bus=sheet['grid']['bus'][i],
                             vm_pu=sheet['grid']['vm_pu'][i],
                             va_degree=sheet['grid']['va_degree'][i],
                             max_p_mw=sheet['grid']['max_p_mw'][i],
                             min_p_mw=sheet['grid']['min_p_mw'][i],
                             max_q_mvar=sheet['grid']['max_q_mvar'][i],
                             min_q_mvar=sheet['grid']['min_q_mvar'][i],
                             in_service=sheet['grid']['in_service'][i],
                             controllable=sheet['grid']['controllable'][i]
                            )
net.ext_grid

,name,bus,vm_pu,va_degree,slack_weight,in_service,controllable,min_p_mw,max_p_mw,min_q_mvar,max_q_mvar
0,grid,0,1.06,0.0,1.0,True,True,0.0,320.0,300.0,-160.0

In [10]:
#create capacitor shunt
caps={}

for i in range(len(sheet['shunt'])):
    caps[i]=create_shunt(net, name=sheet['shunt']['name'][i],
                         bus=sheet['shunt']['bus'][i],
                         q_mvar=sheet['shunt']['q_mvar'][i],
                         p_mw=sheet['shunt']['p_mw'][i],
                         in_service=sheet['shunt']['in_service'][i],
                         step=sheet['shunt']['step'][i],
                         max_step=sheet['shunt']['max_step'][i]
                        )
net.shunt

,bus,name,q_mvar,p_mw,vn_kv,step,max_step,id_characteristic_table,step_dependency_table,in_service
0,8,cap1,19.326701,0.0,33.0,1,1,<NA>,False,True

In [11]:
#run load flow
runpp(net)

In [12]:
#display external grid
net.res_ext_grid

         p_mw     q_mvar
0  233.061252 -20.096509

In [13]:
#display generator loading
net.res_gen

   p_mw     q_mvar  va_degree  vm_pu
0  40.0  36.934241  -4.971033  1.045
1   0.0  22.422740 -12.671328  1.010
2   0.0  61.380227 -15.172561  1.070
3   0.0  38.285484 -13.400883  1.090

In [14]:
#display trafo loading
net.res_trafo['loading_percent']

0    26.671382
1    15.505672
2    48.430366
3    35.124298
4    37.377239
Name: loading_percent, dtype: float64

In [15]:
#display line loading
net.res_line['loading_percent']

0     32.552795
1     32.552795
2     31.578284
3     30.565920
4     23.383662
5     17.645060
6     10.399436
7     25.460928
8     28.757061
9     15.087402
10    37.543715
11    13.611454
12    15.374788
13    23.402466
14     5.087661
15    19.220358
Name: loading_percent, dtype: float64

In [16]:
#display bus voltage
net.res_bus['vm_pu']

0     1.060000
1     1.045000
2     1.010000
3     1.021379
4     1.029232
5     1.070000
6     1.029997
7     1.090000
8     1.001629
9     1.005972
10    1.033903
11    1.051041
12    1.042393
13    1.000770
Name: vm_pu, dtype: float64

In [17]:
#display shunt
net.shunt

,bus,name,q_mvar,p_mw,vn_kv,step,max_step,id_characteristic_table,step_dependency_table,in_service
0,8,cap1,19.326701,0.0,33.0,1,1,<NA>,False,True

In [18]:
from pandapower import to_pickle
to_pickle(net, "ieee14bus.p")

In [19]:
net.ext_grid.vm_pu[0]

np.float64(1.06)

In [23]:
net.ext_grid.bus.values + net.gen.bus.values + net.shunt.bus.values

array([ 9, 10, 13, 15], dtype=uint32)