In [18]:
from pandapower.create import (
    create_empty_network,
    create_bus,
    create_gen,
    create_load,
    create_line_from_parameters,
    create_transformer_from_parameters,
    create_ext_grid,
    create_shunt
)

from pandapower.run import runpp

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [19]:
#read xlsx file
import pandas as pd

xls = pd.ExcelFile('ieee39bus.xlsx')

xls.sheet_names

sheet = {}

for sheet_name in xls.sheet_names:
    sheet[sheet_name] = xls.parse(sheet_name)

In [20]:
net = create_empty_network()

In [21]:
#read bus data
buses = {}

for i in range(len(sheet['bus'])):
    buses[i] = create_bus(net, vn_kv=sheet['bus']['vn_kv'][i],
                          name=sheet['bus']['name'][i],
                          type=sheet['bus']['type'][i],
                          in_service=sheet['bus']['in_service'][i],
                          max_vm_pu=sheet['bus']['max_vm_pu'][i],
                          min_vm_pu=sheet['bus']['min_vm_pu'][i])
net.bus

     name   vn_kv type  zone  in_service   geo  min_vm_pu  max_vm_pu
0    bus1  345.00    b  None        True  None        0.9        1.1
1    bus2  345.00    b  None        True  None        0.9        1.1
2    bus3  345.00    b  None        True  None        0.9        1.1
3    bus4  345.00    b  None        True  None        0.9        1.1
4    bus5  345.00    b  None        True  None        0.9        1.1
5    bus6  345.00    b  None        True  None        0.9        1.1
6    bus7  345.00    b  None        True  None        0.9        1.1
7    bus8  345.00    b  None        True  None        0.9        1.1
8    bus9  345.00    b  None        True  None        0.9        1.1
9   bus10  345.00    b  None        True  None        0.9        1.1
10  bus11  345.00    b  None        True  None        0.9        1.1
11  bus12  138.00    b  None        True  None        0.9        1.1
12  bus13  345.00    b  None        True  None        0.9        1.1
13  bus14  345.00    b  None        True  None        0.9        1.1
14  bus15  345.00    b  None        True  None        0.9        1.1
15  bus16  345.00    b  None        True  None        0.9        1.1
16  bus17  345.00    b  None        True  None        0.9        1.1
17  bus18  345.00    b  None        True  None        0.9        1.1
18  bus19  345.00    b  None        True  None        0.9        1.1
19  bus20  230.00    b  None        True  None        0.9        1.1
20  bus21  345.00    b  None        True  None        0.9        1.1
21  bus22  345.00    b  None        True  None        0.9        1.1
22  bus23  345.00    b  None        True  None        0.9        1.1
23  bus24  345.00    b  None        True  None        0.9        1.1
24  bus25  345.00    b  None        True  None        0.9        1.1
25  bus26  345.00    b  None        True  None        0.9        1.1
26  bus27  345.00    b  None        True  None        0.9        1.1
27  bus28  345.00    b  None        True  None        0.9        1.1
28  bus29  345.00    b  None        True  None        0.9        1.1
29  bus30   16.05    b  None        True  None        0.9        1.1
30  bus31   16.05    b  None        True  None        0.9        1.1
31  bus32   16.05    b  None        True  None        0.9        1.1
32  bus33   16.05    b  None        True  None        0.9        1.1
33  bus34   16.05    b  None        True  None        0.9        1.1
34  bus35   16.05    b  None        True  None        0.9        1.1
35  bus36   16.05    b  None        True  None        0.9        1.1
36  bus37   16.05    b  None        True  None        0.9        1.1
37  bus38   16.05    b  None        True  None        0.9        1.1
38  bus39  345.00    b  None        True  None        0.9        1.1

In [22]:
#read generator data
gens = {}

for i in range(len(sheet['gen'])):
    gens[i] = create_gen(net, name=sheet['gen']['name'][i],
                         bus=sheet['gen']['bus'][i],
                         p_mw=sheet['gen']['p_mw'][i],
                         vm_pu=sheet['gen']['vm_pu'][i],
                         sn_mva=sheet['gen']['sn_mva'][i],
                         min_q_mvar=sheet['gen']['min_q_mvar'][i],
                         max_q_mvar=sheet['gen']['max_q_mvar'][i],
                         controllable=sheet['gen']['controllable'][i],
                         in_service=sheet['gen']['in_service'][i],
                         min_p_mw=sheet['gen']['min_p_mw'][i],
                         max_p_mw=sheet['gen']['max_p_mw'][i],
                        )
net.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,controllable,id_q_capability_characteristic,reactive_capability_curve,curve_style,in_service,slack_weight,type,min_p_mw,max_p_mw
0,gen1,38,1000.0,1.0300,10000.0,-3000.0,7000.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,0.0,8500.0
1,gen3,31,650.0,0.9831,800.0,-240.0,560.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,200.0,680.0
2,gen4,32,632.0,0.9972,800.0,-240.0,560.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,200.0,680.0
3,gen5,33,508.0,1.0123,300.0,-90.0,210.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,70.0,255.0
4,gen6,34,650.0,1.0493,800.0,-240.0,560.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,200.0,680.0
5,gen7,35,560.0,1.0635,700.0,-210.0,490.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,150.0,595.0
6,gen8,36,540.0,1.0278,700.0,-210.0,490.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,150.0,595.0
7,gen9,37,830.0,1.0265,1000.0,-300.0,700.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,250.0,850.0
8,gen10,29,250.0,1.0475,1000.0,-500.0,600.0,1.0,False,False,<NA>,False,NaN,True,0.0,None,0.0,850.0

In [23]:
#read transformer data
trafos={}

for i in range(len(sheet['trafo'])):
    trafos[i] = create_transformer_from_parameters(net, name=sheet['trafo']['name'][i],
                             hv_bus=sheet['trafo']['hv_bus'][i],
                             lv_bus=sheet['trafo']['lv_bus'][i],
                             sn_mva=sheet['trafo']['sn_mva'][i],
                             vn_hv_kv=sheet['trafo']['vn_hv_kv'][i],
                             vn_lv_kv=sheet['trafo']['vn_lv_kv'][i],
                             vkr_percent=sheet['trafo']['vkr_percent'][i],
                             vk_percent=sheet['trafo']['vk_percent'][i],
                             pfe_kw=sheet['trafo']['pfe_kw'][i],
                             i0_percent=sheet['trafo']['i0_percent'][i],
                             vector_group=sheet['trafo']['vector_group'][i],
                             vk0_percent=sheet['trafo']['vk0_percent'][i],
                             in_service=sheet['trafo']['in_service'][i],
                             shift_degree=sheet['trafo']['shift_degree'][i],
                             tap_side=sheet['trafo']['tap_side'][i],
                             tap_neutral=sheet['trafo']['tap_neutral'][i],
                             tap_max=sheet['trafo']['tap_max'][i],
                             tap_min=sheet['trafo']['tap_min'][i],
                             tap_step_percent=sheet['trafo']['tap_step_percent'][i],
                             max_loading_percent=sheet['trafo']['max_loading_percent'][i]
                            )
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,tap_changer_type,id_characteristic_table,tap_dependency_table,parallel,df,in_service,vk0_percent,vector_group,max_loading_percent,oltc
0,trafo1,None,1,29,1000.0,345.0,16.5,18.10000,0.00000,0.0,...,NaN,<NA>,False,1,1.0,True,18.10000,Yny,100.0,False
1,trafo2,None,5,30,700.0,345.0,16.5,17.50000,0.00000,0.0,...,NaN,<NA>,False,1,1.0,True,17.50000,Yny,100.0,False
2,trafo3,None,9,31,800.0,345.0,16.5,16.00000,0.00000,0.0,...,NaN,<NA>,False,1,1.0,True,16.00000,Yny,100.0,False
3,trafo4,None,10,11,300.0,345.0,138.0,13.05882,0.48000,0.0,...,NaN,<NA>,False,1,1.0,True,13.05882,Yny,100.0,False
4,trafo5,None,12,11,300.0,345.0,138.0,13.05882,0.48000,0.0,...,NaN,<NA>,False,1,1.0,True,13.05882,Yny,100.0,False
5,trafo6,None,18,19,1000.0,345.0,230.0,13.81774,0.69999,0.0,...,NaN,<NA>,False,1,1.0,True,13.81774,Yny,100.0,False
6,trafo7,None,18,32,800.0,345.0,16.5,11.37379,0.56000,0.0,...,NaN,<NA>,False,1,1.0,True,11.37379,Yny,100.0,False
7,trafo8,None,19,33,600.0,230.0,16.5,10.81349,0.54000,0.0,...,NaN,<NA>,False,1,1.0,True,10.81349,Yny,100.0,False
8,trafo9,None,21,34,800.0,345.0,16.5,11.44000,0.00000,0.0,...,NaN,<NA>,False,1,1.0,True,11.40000,Yny,100.0,False
9,trafo10,None,22,35,700.0,345.0,16.5,19.04322,0.35000,0.0,...,NaN,<NA>,False,1,1.0,True,19.04322,Yny,100.0,False
10,trafo11,None,24,36,700.0,345.0,16.5,16.24543,0.42000,0.0,...,NaN,<NA>,False,1,1.0,True,16.24543,Yny,100.0,False
11,trafo12,None,28,37,1000.0,345.0,16.5,15.62050,0.80000,0.0,...,NaN,<NA>,False,1,1.0,True,15.62050,Yny,100.0,False

In [24]:
#read line data
lines={}

for i in range(len(sheet['line'])):
    lines[i]=create_line_from_parameters(net, name=sheet['line']['name'][i],
                                         from_bus=sheet['line']['from_bus'][i],
                                         to_bus=sheet['line']['to_bus'][i],
                                         length_km=sheet['line']['length_km'][i],
                                         r_ohm_per_km=sheet['line']['r_ohm_per_km'][i],
                                         x_ohm_per_km=sheet['line']['x_ohm_per_km'][i],
                                         c_nf_per_km=sheet['line']['c_nf_per_km'][i],
                                         max_i_ka=sheet['line']['max_i_ka'][i],
                                         in_service=sheet['line']['in_service'][i], 
                                         type=sheet['line']['type'][i],
                                         max_loading_percent=sheet['line']['max_loading_percent'][i]
                                        )
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service,geo,max_loading_percent
0,Line 01 - 02,None,0,1,163.06430,0.025547,0.3,9.54910,0.0,1.0,1.0,1,ol,True,None,100.0
1,Line 01 - 39,None,0,38,99.18750,0.012000,0.3,16.85140,0.0,1.0,1.0,1,ol,True,None,100.0
2,Line 02 - 03,None,1,2,59.90925,0.025828,0.3,9.56770,0.0,1.0,1.0,1,ol,True,None,100.0
3,Line 02 - 25,None,1,24,34.12050,0.244186,0.3,9.53600,0.0,1.0,1.0,1,ol,True,None,100.0
4,Line 03 - 04,None,2,3,84.50775,0.018310,0.3,5.83860,0.0,1.0,1.0,1,ol,True,None,100.0
5,Line 03 - 18,None,2,17,52.76775,0.024812,0.3,9.02960,0.0,1.0,1.0,1,ol,True,None,100.0
6,Line 04 - 05,None,3,4,50.78400,0.018750,0.3,18.75000,0.0,1.0,1.0,1,ol,True,None,100.0
7,Line 04 - 14,None,3,13,51.18075,0.018605,0.3,18.60465,0.0,1.0,1.0,1,ol,True,None,100.0
8,Line 05 - 06,None,4,5,10.31550,0.023077,0.3,9.37630,0.0,1.0,1.0,1,ol,True,None,100.0
9,Line 05 - 08,None,4,7,44.43600,0.021429,0.3,7.40260,0.0,1.0,1.0,1,ol,True,None,100.0
10,Line 06 - 07,None,5,6,36.50100,0.019565,0.3,6.89930,0.0,1.0,1.0,1,ol,True,None,100.0
11,Line 06 - 11,None,5,10,32.53350,0.025610,0.3,9.51490,0.0,1.0,1.0,1,ol,True,None,100.0
12,Line 07 - 08,None,6,7,18.25050,0.026087,0.3,9.52470,0.0,1.0,1.0,1,ol,True,None,100.0
13,Line 08 - 09,None,7,8,144.02020,0.019008,0.3,5.88640,0.0,1.0,1.0,1,ol,True,None,100.0
14,Line 09 - 39,None,8,38,99.18750,0.012000,0.3,26.96220,0.0,1.0,1.0,1,ol,True,None,100.0
15,Line 10 - 11,None,9,10,17.06025,0.027907,0.3,9.52300,0.0,1.0,1.0,1,ol,True,None,100.0
16,Line 10 - 13,None,9,12,17.06025,0.027907,0.3,9.52300,0.0,1.0,1.0,1,ol,True,None,100.0
17,Line 13 - 14,None,12,13,40.07175,0.026733,0.3,9.58250,0.0,1.0,1.0,1,ol,True,None,100.0
18,Line 14 - 15,None,13,14,86.09475,0.024885,0.3,9.47400,0.0,1.0,1.0,1,ol,True,None,100.0
19,Line 15 - 16,None,14,15,37.29450,0.028723,0.3,10.21840,0.0,1.0,1.0,1,ol,True,None,100.0
20,Line 16 - 17,None,15,16,35.31075,0.023596,0.3,8.46990,0.0,1.0,1.0,1,ol,True,None,100.0
21,Line 16 - 19,None,15,18,77.36625,0.024615,0.3,8.75690,0.0,1.0,1.0,1,ol,True,None,100.0
22,Line 16 - 21,None,15,20,53.56125,0.017778,0.3,10.60180,0.0,1.0,1.0,1,ol,True,None,100.0
23,Line 16 - 24,None,15,23,23.40825,0.015254,0.3,6.47400,0.0,1.0,1.0,1,ol,True,None,100.0
24,Line 17 - 18,None,16,17,32.53350,0.025610,0.3,9.03530,0.0,1.0,1.0,1,ol,True,None,100.0
25,Line 17 - 27,None,16,26,68.63775,0.022543,0.3,10.44200,0.0,1.0,1.0,1,ol,True,None,100.0
26,Line 21 - 22,None,20,21,55.54500,0.017143,0.3,10.29140,0.0,1.0,1.0,1,ol,True,None,100.0
27,Line 22 - 23,None,21,22,38.08800,0.018750,0.3,10.80130,0.0,1.0,1.0,1,ol,True,None,100.0
28,Line 23 - 24,None,22,23,138.86250,0.018857,0.3,5.79370,0.0,1.0,1.0,1,ol,True,None,100.0
29,Line 25 - 26,None,24,25,128.15030,0.029721,0.3,8.92130,0.0,1.0,1.0,1,ol,True,None,100.0
30,Line 26 - 27,None,25,26,58.32225,0.028571,0.3,9.15550,0.0,1.0,1.0,1,ol,True,None,100.0
31,Line 26 - 28,None,25,27,188.05950,0.027215,0.3,9.24570,0.0,1.0,1.0,1,ol,True,None,100.0
32,Line 26 - 29,None,25,28,247.96880,0.027360,0.3,9.24800,0.0,1.0,1.0,1,ol,True,None,100.0
33,Line 28 - 29,None,27,28,59.90925,0.027815,0.3,9.26270,0.0,1.0,1.0,1,ol,True,None,100.0

In [25]:
#read load data
loads={}

for i in range(len(sheet['load'])):
    loads[i]=create_load(net, name=sheet['load']['name'][i],
                         bus=sheet['load']['bus'][i],
                         p_mw=sheet['load']['p_mw'][i],
                         q_mvar=sheet['load']['q_mvar'][i],
                         in_service=sheet['load']['in_service'][i],
                         type=sheet['load']['type'][i],
                         controllable=sheet['load']['controllable'][i]
                        )
net.load

,name,bus,p_mw,q_mvar,const_z_p_percent,const_i_p_percent,const_z_q_percent,const_i_q_percent,sn_mva,scaling,in_service,type,controllable
0,load1,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
1,load2,1,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
2,load3,2,322.0,2.4,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
3,load4,3,500.0,184.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
4,load5,4,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
5,load6,5,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
6,load7,6,233.8,84.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
7,load8,7,522.0,176.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
8,load9,8,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
9,load10,9,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
10,load11,10,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
11,load12,11,7.5,88.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
12,load13,12,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
13,load14,13,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
14,load15,14,320.0,153.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
15,load16,15,329.0,32.3,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
16,load17,16,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
17,load18,17,158.0,30.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
18,load19,18,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
19,load20,19,628.0,103.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
20,load21,20,274.0,115.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
21,load22,21,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
22,load23,22,247.5,84.6,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
23,load24,23,308.6,-92.2,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
24,load25,24,224.0,47.2,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
25,load26,25,139.0,17.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
26,load27,26,281.0,75.5,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
27,load28,27,206.0,27.6,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
28,load29,28,283.5,26.9,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
29,load30,29,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
30,load31,30,9.2,4.6,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
31,load32,31,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
32,load33,32,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
33,load34,33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
34,load35,34,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
35,load36,35,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
36,load37,36,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
37,load38,37,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False
38,load39,38,1104.0,250.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye,False

In [26]:
#create external grid
grids={}

for i in range(len(sheet['grid'])):
    grids[i]=create_ext_grid(net, name=sheet['grid']['name'][i],
                             bus=sheet['grid']['bus'][i],
                             vm_pu=sheet['grid']['vm_pu'][i],
                             va_degree=sheet['grid']['va_degree'][i],
                             max_p_mw=sheet['grid']['max_p_mw'][i],
                             min_p_mw=sheet['grid']['min_p_mw'][i],
                             max_q_mvar=sheet['grid']['max_q_mvar'][i],
                             min_q_mvar=sheet['grid']['min_q_mvar'][i],
                             in_service=sheet['grid']['in_service'][i],
                             controllable=sheet['grid']['controllable'][i]
                            )
net.ext_grid

,name,bus,vm_pu,va_degree,slack_weight,in_service,controllable,min_p_mw,max_p_mw,min_q_mvar,max_q_mvar
0,grid,30,0.982,0.0,1.0,True,True,150.0,595.0,-210.0,490.0

In [27]:
#run load flow
runpp(net)

In [28]:
#display external grid
net.res_ext_grid

         p_mw      q_mvar
0  528.088947  146.343138

In [29]:
#display generator loading
net.res_gen

     p_mw      q_mvar  va_degree   vm_pu
0  1000.0  341.068752 -11.090835  1.0300
1   650.0  155.977653   2.940664  0.9831
2   632.0   70.176777   5.192496  0.9972
3   508.0  147.529346   4.122847  1.0123
4   650.0  253.717445   6.577292  1.0493
5   560.0  209.338354   9.568779  1.0635
6   540.0   29.487273   2.659152  1.0278
7   830.0   89.306055   8.826007  1.0265
8   250.0  169.076133  -3.616144  1.0475

In [30]:
#display trafo loading
net.res_trafo['loading_percent']

0     29.619823
1     80.445408
2     87.375951
3     15.692995
4     16.763800
5     12.827803
6     81.943540
7     89.535386
8     85.452916
9     82.558985
10    77.275628
11    83.604100
Name: loading_percent, dtype: float64

In [31]:
#display line loading
net.res_line['loading_percent']

0      29.077563
1      23.446617
2      68.326027
3      44.883613
4      31.030898
5      10.942627
6      25.946021
7      48.969755
8      82.771841
9      57.282706
10     76.455952
11     64.986679
12     34.543044
13     36.368347
14     31.315614
15     65.391722
16     51.780063
17     50.569469
18      5.956349
19     62.415271
20     41.859444
21     88.292616
22     57.744055
23     24.668842
24     36.827817
25      8.269203
26    107.830246
27      8.326024
28     61.491967
29     16.304168
30     48.081108
31     24.785123
32     33.189430
33     59.234774
Name: loading_percent, dtype: float64

In [32]:
#display bus voltage
net.res_bus['vm_pu']

0     1.022688
1     0.989894
2     0.960114
3     0.926616
4     0.927070
5     0.928110
6     0.920827
7     0.922120
8     0.995782
9     0.933617
10    0.930257
11    0.909774
12    0.931504
13    0.931510
14    0.935686
15    0.954429
16    0.957911
17    0.957021
18    0.959591
19    0.957464
20    0.961251
21    0.989336
22    0.987633
23    0.962688
24    0.997565
25    0.980533
26    0.963114
27    0.982627
28    0.986368
29    1.047500
30    0.982000
31    0.983100
32    0.997200
33    1.012300
34    1.049300
35    1.063500
36    1.027800
37    1.026500
38    1.030000
Name: vm_pu, dtype: float64

In [33]:
from pandapower import to_pickle
to_pickle(net, "ieee39bus.p")